
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'planACTION CONJUNCTION GOAL INFINITIVE OBJECTCOMPLEMENT PREPOSITION SPATIALOCATION TOOLCOMPLEMENTplan : actionFirst INFINITIVE GOAL OBJECTCOMPLEMENT SPATIALOCATIONplan : actionFirst INFINITIVE GOAL OBJECTCOMPLEMENT SPATIALOCATION PREPOSITION OBJECTCOMPLEMENT SPATIALOCATIONactionFirst : actionFirst CONJUNCTION actionFirstactionFirst : ACTION TOOLCOMPLEMENT OBJECTCOMPLEMENT'
    
_lr_action_items = {'ACTION':([0,5,],[3,3,]),'$end':([1,11,14,],[0,-1,-2,]),'INFINITIVE':([2,8,9,],[4,-3,-4,]),'CONJUNCTION':([2,8,9,],[5,5,-4,]),'TOOLCOMPLEMENT':([3,],[6,]),'GOAL':([4,],[7,]),'OBJECTCOMPLEMENT':([6,7,12,],[9,10,13,]),'SPATIALOCATION':([10,13,],[11,14,]),'PREPOSITION':([11,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'plan':([0,],[1,]),'actionFirst':([0,5,],[2,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> plan","S'",1,None,None,None),
  ('plan -> actionFirst INFINITIVE GOAL OBJECTCOMPLEMENT SPATIALOCATION','plan',5,'p_plan_spatialPositions_openOnly','motionparser.py',15),
  ('plan -> actionFirst INFINITIVE GOAL OBJECTCOMPLEMENT SPATIALOCATION PREPOSITION OBJECTCOMPLEMENT SPATIALOCATION','plan',8,'p_plan_spatialPositions','motionparser.py',20),
  ('actionFirst -> actionFirst CONJUNCTION actionFirst','actionFirst',3,'p_actionFirst_conj','motionparser.py',25),
  ('actionFirst -> ACTION TOOLCOMPLEMENT OBJECTCOMPLEMENT','actionFirst',3,'p_actionFirst_complements','motionparser.py',29),
]
