'''
    File name: fastdownward.py
    Author: David Carmona
    Date created: 01/12/2022
    Date last modified: 17/11/2025
    Python Version: 3.10 (64-bit)
    Description: Launch Fast Downward planner from Python code
'''
import logging
import os
import sys
import time
import numpy as np
from argparse import Namespace
import pandas as pandas

from classical_task_planning.Fast_Downward.driver import aliases
from classical_task_planning.Fast_Downward.driver import arguments
from classical_task_planning.Fast_Downward.driver import cleanup
from classical_task_planning.Fast_Downward.driver import run_components
from classical_task_planning.Fast_Downward.driver import __version__

import Language_Model_many2many_novelty.utils_file_string as utils_file_string

# Fast Downward class. It allows running Fast Downward from Python code
class FastDownward:

	# The plan generated by Fast Downward
	plan = [];

	# Total time taken by Fast Downward to generate the plan for the specified task
	total_taskPlanning_time = 0;

	# Class constructor
	# @input algo Type of algorithm that is used to run FD. Different possibilities: astar(cg()) or lazy_greedy([cg(),ff()]) or lazy_greedy([cg()])
	# @input task Task specified in the PDDL format that Fast Downward must execute
	# @input line_to_modify Integer. Line to modify inside the pddl file (Line 14 to modify the goal and Line 6 for the objects' locations)
	# @input problemfilename String. The name of the PDDL problem definition file.
	# @input domainfilename String. The name of the PDDL domain definition file.
	def __init__(self,task,algo,line_to_modify,problemfilename,domainfilename):
		if type(algo)!=str or algo=='' or type(task)!=str or task=='' or type(line_to_modify)!=int or line_to_modify<0:
			raise Exception("[fastdownward.py] Wrong input");
		if type(problemfilename)!=str or problemfilename=='' or type(domainfilename)!=str or domainfilename=='':
			raise Exception("[fastdownward.py] Wrong input");

		# Modify the PDDL problem definition file to account for the task that the user wants to execute
		pddlProblem_filename = os.path.join(os.path.dirname(__file__),'Fast_Downward',problemfilename);
		utils_file_string.modify_text_line(pddlProblem_filename,line_to_modify,task);# The line to modify is always line #14. Never change!

		# Times
		results_time = [];

		# To use AStar: --search astar(blind()) or --search astar(cg()) 
		# cg() is the Causal Graph Heuristic proposed in the paper
		args = Namespace(alias=None, build='release', cleanup=False, components=['translate', 'search'], 
							debug=False, filenames=[problemfilename], keep_sas_file=False, log_level='silent', 
							overall_memory_limit=None, overall_time_limit=None, plan_file='sas_plan',
							planner_args=[problemfilename, '--search', algo], portfolio=None, 
							portfolio_bound=None, portfolio_single_plan=False, run_all=False, sas_file='output.sas',
							search=False, search_input='output.sas', search_memory_limit=None, search_options=['--search', algo], 
							search_time_limit=None, show_aliases=False, translate=False, translate_inputs=[os.path.join(os.path.dirname(__file__),'Fast_Downward',domainfilename), os.path.join(os.path.dirname(__file__),'Fast_Downward',problemfilename)],
							translate_memory_limit=None, translate_options=['--sas-file', 'output.sas'], translate_time_limit=None, validate=False, 
							validate_memory_limit=None, validate_time_limit=None, version=False, verbosity='silent');
		exitcode = None;
		
		# Run Fast Downward
		start_time = time.time();# Start clock
		(exitcode, continue_execution) = run_components.run_translate(args);# Translatefi
		(exitcode, continue_execution) = run_components.run_search(args);# Validate
		end_time = time.time();# End clock

		# Store the total time taken by Fast Downward to generate the plan for the specified task. In milliseconds
		self.total_taskPlanning_time = (end_time-start_time)*1000;

		# Extract the plan generated by Fast Downward
		self.extract_plan();

	# Get the plan generated by Fast Downward
	# @return The plan generated by Fast Downward
	def get_plan(self):
		return self.plan;

	# Extract the plan generated by Fast Downward from the sas_plan file
	def extract_plan(self):
		self.plan = self.parse_sas_file("sas_plan");

	# Remove useless characters from the lines of the sas_plan file
	# @input lines Lines of the sas_plan file
	# @return The lines without useless characters
	def remove_useless_characters(self,lines):
		list_index = 0;
		for line in lines:
			line = line.replace("(","");# Useless character
			line = line.replace(")","");# Useless character
			line = line.replace("\n","");# Useless character
			lines[list_index] = line;
			list_index = list_index + 1;
		return lines;

	# Extract the actions from the lines of the sas_plan file
	# @input plan_lines Lines of the sas_plan file
	# @return The list of actions
	def extract_actions(self,plan_lines):
		actions_list = [];
		for line in plan_lines:
			actions_list.append(line.split(' ', 1)[0]);
		return actions_list;

	# Extract the arguments from the lines of the sas_plan file
	# @input plan_lines Lines of the sas_plan file
	# @return The list of arguments
	def extract_args(self,plan_lines):
		args_list = []
		for line in plan_lines:
			line = line.split(' ', 1)[1];# First word is the action. The action is useless.
			args = line.split()   ;
			args_list.append(args);
		return args_list;

	# Convert the actions and arguments lists into a dictionary
	# @input actions List of actions
	# @input arguments List of arguments
	# @return The plan in dictionary format
	def convert_to_dict(self,actions,arguments):
		plan_dict = [];
		for k in range(0,len(actions)):
			action_dict ={
				"name": actions[k],
				"args": arguments[k],
			}  
			plan_dict.append(action_dict);
		return plan_dict;

	# Get the plan elements from the lines of the sas_plan file
	# @input plan_lines Lines of the sas_plan file
	# @return The plan elements
	def get_plan_elements(self,plan_lines):
		actions = self.extract_actions(plan_lines);
		arguments = self.extract_args(plan_lines);
		elements = self.convert_to_dict(actions,arguments);
		return elements;

	# Parse the sas_plan file generated by Fast Downward
	# @input filename Name of the sas_plan file
	# @return The plan elements
	def parse_sas_file(self,filename):
		plan_file = open(filename,'r');
		plan_lines = self.remove_useless_characters(plan_file.readlines());
		plan_elements = self.get_plan_elements(plan_lines);
		return plan_elements;

	# Get the total time taken by Fast Downward to generate the plan for the specified task
	# @return The total time taken by Fast Downward to generate the plan for the specified
	def get_total_taskPlanning_time(self):
		return self.total_taskPlanning_time;

def main():
	planner_FD = FastDownward('(:goal (and (passed wood_block 15 experimenter_hand 7)))) \n','astar(cg())',14,'task_Exp4_pass.pddl','domain_3_pass.pddl');
	print("time: ",planner_FD.get_total_taskPlanning_time());
		
if __name__ == "__main__":
	main();